# com.rest.angular_api package의 하위 로그는 debug level 이상일때 출력되도록한다.
# 나머지 로그들은 warn level 이상이어야 출력된다.
logging:
  level:
    root: info
    com.rest.angular_api: debug

spring:
  profiles: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/angular
    driver-class-name: org.h2.Driver
    username: sa


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate:
      hbm2ddl.auto: update
      format_sql: true
    showSql: true
    generate-ddl: true
  url:
    base: http://localhost:8080
  redis:
    host: localhost
    port: 6379

