#alpah 설정 환경
#
logging:
  level:
    root: warn
    com.rest.angular_api: info
  path: /home/ec2-user/api/log
  file:
    max-history: 7

spring:
  profiles: alpha
  datasource:
    url: jdbc:mysql://fullstack-maria-db.cqn5x65cmexd.ap-northeast-2.rds.amazonaws.com:3306/FullstackDB?useUnicode=true&autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true&sueSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: joshua
    password: 4tkfkdwlrl
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate:
      hbm2ddl.auto: none
      format_sql: true
    showSql: true
    generate-ddl: false
  url:
    base : http://alpha.mj.org