#alpah 설정 환경

logging:
  level:
    root: warn
    com.rest.angular_api: info
  path: /home/ec2-user/api/log
  file:
    max-history: 7

spring:
  profiles: alpha
  datasource:
    url: jdbc:mysql://
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate:
      hbm2ddl.auto: none
      format_sql: true
    showSql: true
    generate-ddl: false
  url:
    base : http://alpha.mj.org